  version: '3'
  services:
  # Nginxサービス
   nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./:/src  # ソースコードのマウント（変更点） 
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  # PHPアプリケーションサービス
   app:
    container_name: app
    build:
      context: ./docker/php
    volumes:
      - ./:/src  # ソースコードのマウント（変更点）
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
